### ISSUE TITLE
failed extract queries from components

### ISSUE THREAD

**Issue by jaflonu** [EmaSuriano/gatsby-starter-mate#195]
Everything was going fine, until from nothing, I had this issue and I could not solve it. This is what I get on the terminal:

```
ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "contentfulAbout" on type "Query".

If you don't expect "contentfulAbout" to exist on the type "Query" it is most likely a typo.
However, if you expect "contentfulAbout" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "contentfulAbout" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/sections/About.js:50:11
```

**Comment by jaflonu** [comment]
I've joust fixed it. I fucked up the content model id

**Comment by jung-youjin** [comment]
Hi, I'm facing the same issue. Could you tell me how you solved this problem? Thanks!

**Comment by jakrim** [comment]
Hi also facing the issues. I know @EmaSuriano merged and created a fix with the latest code - but Ema I can't figure out how to merge your code with mine? I also added an iFrame with my resume so don't want to get that overridden! Need a workflow... Sorry to be a bother.  

Getting this error:  ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "contentfulAbout" on type "Query".

**Comment by EmaSuriano** [comment]
Hi @jung-youjin are you still facing this issue with the new setup with themes?

**Comment by jung-youjin** [comment]
@EmaSuriano Nope! I got this fixed and everything's fine now :) Thanks for keeping up!
