### ISSUE TITLE
Removing Medium Dependencies

### ISSUE THREAD

**Issue by oscarmrom** [EmaSuriano/gatsby-starter-mate#22]
Hello, thanks for creating this starter!

I'm running into a build error when I get rid of the Medium user field in Contentful. 

```
Fetch Contentful data: 780.202ms
{ Error: Request failed with status code 404
```

I won't be using Medium so what in the codebase (just cloned it and haven't changed anything) do I have to remove to be able to strip Medium dependencies and calls?

If possible, this would be a great addition to your documentation.

Thank you in advance!

**Comment by EmaSuriano** [comment]
Hey @oscarmrom great recommendation to add to the starter. Yes, you're right if the `mediumUser` is not provided inside the About entity, then the build step fails. Therefore I opened [this pull request](#23 ), I'm not really sure this is the best approach of doing it so if you know a better way please tell me  🙏 

Please review it and tell me if this fix your issues :)

**Comment by EmaSuriano** [comment]
#23

**Comment by EmaSuriano** [comment]
Hi @oscarmrom, the PR has been merged and now if you don't set your medium user inside Contentful, the Writing section won't be displayed at the bottom. Hope you can use this starter now 😄 
I'll close the issue, please feel free to reopen it in case you encounter any problem 👍
