### ISSUE TITLE
Bug: URL of cards in writing section

### ISSUE THREAD

**Issue by Crayon-ShinChan** [EmaSuriano/gatsby-starter-mate#258]
The url for the cards in writing section should be added '@', especially in `MorePosts`.

The original code:
```JavaScript
const MorePosts = ({ username, name, number }) => (
  <Card
    onClick={() => window.open(`${MEDIUM_URL}/${username}/`, '_blank')}
    p={4}
  >
  ...
)
```

We'll get 404 if we use `${MEDIUM_URL}/${username}/`, so we need use `${MEDIUM_URL}/@${username}/` instead.

For other normal post cards (not `MorePosts`), it's ok to use the url without `@`, because somehow the `@` can be added automatically when we open these posts' url. But it's better to add `@` in our code as well.

**Comment by EmaSuriano** [comment]
Fixed with this commit --> https://github.com/EmaSuriano/gatsby-starter-mate/commit/808fe9d6c6f355a0e60641c469c44c2d1609bf59
