### ISSUE TITLE
open and validate gatsby-config[warning] Server 504 error occurred.

### ISSUE THREAD

**Issue by Paddy-Hamilton** [EmaSuriano/gatsby-starter-mate#3]
Hi, 

Love the look of this project. 

I'm just running into a problem when i try and run ``yarn develope`` i get the error 
``open and validate gatsby-config[warning] Server 504 error occurred.Waiting for xxxx ms before retrying...``

I've tried googling around this issue but haven't found anything.  Do you have an idea what could be going wrong ?

Cheers

**Comment by EmaSuriano** [comment]
Hi, thank you for trying the starter! Let's see if I can help you, as I understand you are the last step of the setup. So by this point, you should have your own `Contentful` space with all the date from the starter and also `.env` file in your project with the `SPACE_ID` and `ACCESS_TOKEN`. If not please check.

If everything is ok, could you please paste me all your logs from the terminal that throws `yarn develop`?

**Comment by Paddy-Hamilton** [comment]
Hi,

Yup at the last stage, have the ``SPACE_ID`` and ``ACCESS_TOKEN`` place. If i leave it running ``open and validate gatsby-config[warning]....`` continues for show and few times approx 8-9 and then it goes through. so it does work but the setup takes quite a while.  

This is compared to the gatsby starter project which when I replace the Mate ``gatsby-config``  file with the gatsby starter project config file, it flies through set up really quickly without any errors. I wonder if the issue is connecting with contentful? 

I will run it again later today (after work) and share the full log output.

**Comment by EmaSuriano** [comment]
Do you have a repository that I can clone and see the problem by my self?

**Comment by Paddy-Hamilton** [comment]
I haven't changed anything from running the set up steps so my repo is the same as ``gatsby-starter-mate`` 

I'm running node version 10.11.0

**Comment by EmaSuriano** [comment]
I was able to run the server with node `v10.9.0`, so I'm not able to reproduce this issue.
Anyway, you can see if anyone had the same the problem in (gatsby-contentful-starter)[https://github.com/contentful-userland/gatsby-contentful-starter]. Because this starter has a very similar structure.
Sorry I wasn't able to fix your problem  😞
