### ISSUE TITLE
Add Linkedin to social connections

### ISSUE THREAD

**Issue by 05nelsonm** [EmaSuriano/gatsby-starter-mate#303]

**Comment by 05nelsonm** [comment]
never mind......

**Comment by ajay426** [comment]
Hi @05nelsonm !
Did you manage to show the `LinkedIn` icon?
I tried to show the `LinkedIn` icon by passing `linkedin-in` and `linkedin` but with no luck. It's showing nothing on the page.

**Comment by ajaykumar97** [comment]
For those who are looking for the same thing.
In the file `src/utils/icon-loader.ts` file, import `faLinkedin` from `@fortawesome/free-brands-svg-icons` and add into the array `loadIcons` as shown in the screenshot:

<img width="849" alt="Screenshot 2021-02-19 at 8 50 47 PM" src="https://user-images.githubusercontent.com/38132295/108524192-c7868280-72f4-11eb-9b3e-bd3f3b42b6b1.png">

Then update the `contentful` for the `About` section and set the icon name for the social link to be `linkedin`:

<img width="767" alt="Screenshot 2021-02-19 at 8 57 13 PM" src="https://user-images.githubusercontent.com/38132295/108524487-159b8600-72f5-11eb-82ed-a7d0291fab8e.png">
