### ISSUE TITLE
TypeError: Expected parameter acsessToken on inital deploy straight from gatsby website

### ISSUE THREAD

**Issue by Alex61NN5** [EmaSuriano/gatsby-starter-mate#31]
Just clicked on the Try this starter as located here https://www.gatsbyjs.org/starters/EmaSuriano/gatsby-starter-mate/

I went to netlify and it started to deploy and then I got this error message on the deploy

```
1:39:39 PM: Executing user command: gatsby build
1:39:42 PM: error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.
1:39:42 PM: 
1:39:42 PM:   TypeError: Expected parameter accessToken
1:39:42 PM:   
1:39:42 PM:   - contentful.node.js:7095 Module.createClient
1:39:42 PM:     [repo]/[contentful]/dist/contentful.node.js:7095:11
1:39:42 PM:   
1:39:42 PM:   - gatsby-config.js:7 Object.<anonymous>
1:39:42 PM:     /opt/build/repo/gatsby-config.js:7:27
1:39:42 PM:   
1:39:42 PM:   - v8-compile-cache.js:178 Module._compile
1:39:42 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:178:30
1:39:42 PM:   
1:39:42 PM:   - v8-compile-cache.js:159 require
1:39:42 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
1:39:42 PM:   
1:39:42 PM:   - get-config-file.js:33 
1:39:42 PM:     [repo]/[gatsby]/dist/bootstrap/get-config-file.js:33:22
1:39:42 PM:   
1:39:42 PM:   - Generator.next
1:39:42 PM:   
1:39:42 PM:   - debuggability.js:313 Promise._execute
1:39:42 PM:     [repo]/[bluebird]/js/release/debuggability.js:313:9
1:39:42 PM:   
1:39:42 PM:   - promise.js:483 Promise._resolveFromExecutor
1:39:42 PM:     [repo]/[bluebird]/js/release/promise.js:483:18
1:39:42 PM:   
1:39:42 PM: 
1:39:42 PM: Caching artifacts
```

**Comment by Alex61NN5** [comment]
My Bad did not read the docs just came straight from the gatsby site

**Comment by EmaSuriano** [comment]
Thank you for checking the Readme!

**Comment by harjeetkalsi** [comment]
Hi there, I'm trying to deploy this same stater on my netlify account. I have the same error you had, i have read the READ ME and change the build command on my netlify but it still doesnt work :(. How exactly did you do it? Thanks!

**Comment by Alex61NN5** [comment]
@harjeetkalsi the how to start section tells you what you need to know

**Comment by EmaSuriano** [comment]
Hello @harjeetkalsi please remember to set the environment variables inside the Site settings --> Build & Deploy --> Enviroment variables. There you need to use the same values that you have inside the `.env` file of your project. 
This is how it looks like: 
<img width="1229" alt="Screenshot 2019-07-01 at 10 12 54" src="https://user-images.githubusercontent.com/3399429/60420968-27dd2380-9be9-11e9-85ab-d4e7a589c040.png">
