### ISSUE TITLE
Allow building without Contentful

### ISSUE THREAD

**Issue by taskmaster9001** [EmaSuriano/gatsby-starter-mate#32]
can we have a branch that does not require Contentful for editing the content? Would be great for FOSS junkies like me!

**Comment by EmaSuriano** [comment]
Hi @brute4s99, the idea of this starter is using a CMS to detach the data from the application itself, in this case, it's Contentful. So the idea of removing Contentful goes in the opposite direction to the original idea. Also, the application might need to be rewritten in lots of places (every `StaticQuery` using the Contentful graphql API).

The solution I can think about right is to look for an Open Source CMS and I can include a section in the project to change it. But for now, removing the CMS it's not an option.

Hope you understand it and let me know what do you think 😄

**Comment by brute4s99** [comment]
an Open-source alternative would be lovely; thank you for taking the time
to write back, Emanuel ! 🙂

**Comment by EmaSuriano** [comment]
So I was checking Open Source CMS and I think that one good option would be [Grav](https://getgrav.org/). I didn't about its existence before today actually, but it seems like an up to date project and it also has a Gatsby plugin.

If you have another alternative please share it! I'm totally opened to provide an OS alternative 😁

**Comment by robinmetral** [comment]
I'd love to see this happen too @EmaSuriano :heart_eyes: 

However this would mean that every user has to self-host and set up Grav on a server, wouldn't it? How would you do this?

**Comment by brute4s99** [comment]
I think all that's needed is a way to temporarily host Grav on
localhost for managing data, then destroying it after a `gatsby build`
i.e after getting our static site built out of data and the mate
engine.

**Comment by robinmetral** [comment]
Makes sense @brute4s99! I'd be interested to try this out :slightly_smiling_face:

**Comment by EmaSuriano** [comment]
Hey guys, good conversation there. I found [this article](https://snipcart.com/blog/react-graphql-grav-cms-headless-tutorial) that may help you in case you want to play a little bit. I'm a bit short in time right now, but in case you manage to get it to work please send a contribution!

**Comment by brute4s99** [comment]
sure! I'll add this to my bucket list 😄

**Comment by EmaSuriano** [comment]
Hello guys, any progress on this? 😄

**Comment by brute4s99** [comment]
I'm into some other commitments at the moment, but this is just the next
thing on the list! Do you have any IRC nick or telegram handle where I
could catch you later to discuss on this?

**Comment by EmaSuriano** [comment]
Alright, no worries. I use Discord, we can agree on joining a specific channel and we can talk there!

**Comment by brute4s99** [comment]
sure! catch me at @brute4s99 on Discord!

**Comment by ps-george** [comment]
I think Ghost is a good OSS alternative to Contentful: https://ghost.org/docs/concepts/hosting/

I will probably do some work on this, so @brute4s99 if you've made any progress so far let me know let's share.

Before I get round to that, I'm going to fork the repo & strip out all the contentful & replace it just with static/plaintext, if anyone is interested in that @EmaSuriano.

**Comment by brute4s99** [comment]
No, I have moved on to another starter. Good luck on the adventure! I'll
stay subscribed to keep tabs though 😁

Best
Piyush Aggarwal | brute4s99
https://piyush.tech/

**Comment by ps-george** [comment]
I'm curious @brute4s99 , which one?

**Comment by brute4s99** [comment]
https://journal.piyush.tech/a_better_blog/

**Comment by ps-george** [comment]
Heavily inspired by this repository, I stripped it down & took out Contentful. Here's the repo:

https://github.com/good-data-movement/website
https://good-data-movement.github.io

At some point I will turn it into a Gatsby starter :)

**Comment by brute4s99** [comment]
it looks awesome, @ps-george! 

looking forward to the starter.

**Comment by EmaSuriano** [comment]
Closing the issue due to one of the features of the starter is to be integrated with Contentful.
