### ISSUE TITLE
Writing section including medium posts you've clapped at

### ISSUE THREAD

**Issue by 05nelsonm** [EmaSuriano/gatsby-starter-mate#326]
The Writing section for this wonderful project is unfortunately including Medium posts that you have clapped at written by other people, not ones you've written. Is there a way to distinguish between the two using Contentful, or would this require a PR?

**Comment by messaismael** [comment]
@05nelsonm  it is because you did not have any articles on your medium profile, and by default it takes the clapped articles

**Comment by EmaSuriano** [comment]
This issue is related to the gatsby plugin `gatsby-source-medium` I recommend you to check the issues of them 👍
