### ISSUE TITLE
Where do I find the Content Preview API - access token in Contently??

### ISSUE THREAD

**Issue by lionzan** [EmaSuriano/gatsby-starter-mate#445]
Hi Ema,

I am trying to create the Mate starter, but I get into troubles with Contently API keys. With `yaml setup` i get to input the following API parameters:

- Your Space ID
- Your Content Delivery API access token
- Your Content Management API access token

I can find the first and second in the 'Access tokens' page of Contentful, but I can't find `Content Management API access token` in the same page and I don't know where to look for it. I tried to input the value from `Content Preview API - access token` which I see in the page, but then i get the following error:

`Error: Status: 403 - Forbidden - Message: The access token you sent could not be found or is invalid.`

I'm lost! Please help.

L

**Comment by EmaSuriano** [comment]
Hello @lionzan, I had the same problem and I thought more people will face it too. For that, I recorded a video tutorial going through the whole setup --> https://www.youtube.com/watch?v=YviWsypJF9c

Hope it helps :)

**Comment by lionzan** [comment]
Hola @EmaSuriano awesome thanks, sorted out!
