### ISSUE TITLE
[Feature Request] YouTube Integration

### ISSUE THREAD

**Issue by seanjun21** [EmaSuriano/gatsby-starter-mate#46]
Hello, @EmaSuriano 

I really like this starter and I've been thinking about ways to contribute to your project.
I'm a content creator (YouTuber) myself and I thought it would be nice to have a section which operates very much like your Writing (Medium) section -- but instead for YouTube.

So, I made my own version of it based on your Writing section.
It works in a very similar way (with a few configurations):

1. Need to add a section on Contentful called youtubeUser
2. Need to add environment variable called YOUTUBE_API_KEY (on Netlify)
* I added these manually. I was hoping you could help set these up automatically during the initial setup and questionnaire?

You can check out my portfolio - YouTube section.
https://seanjun.netlify.com/

I wanted to create a pull request but looks like I don't have permission to create one.
Would you give me one? I would be awesome to contribute.

**Comment by EmaSuriano** [comment]
Hey @seanjun21, amazing idea! The youtube section looks amazing and also, I saw that you re-use the `Card` component 👏 About contributing to the project you can always fork it, and send a pr with the changes. I wrote a small [document](https://github.com/EmaSuriano/gatsby-starter-mate/blob/master/CONTRIBUTING.md) about it.
Please tell me if you encounter any issue, I would love to have this inside this starter 😄

**Comment by EmaSuriano** [comment]
Closed by #50
