### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by ShahrozTanveer** [EmaSuriano/gatsby-starter-mate#466]
## Couldn't change favicon.
`yarn build` add following line in `public/index.html`
`<link rel="icon" href="/favicon-32x32.png?v=bd811806cc1b8afc275a716b064f3106" type="image/png"/>`

**Comment by EmaSuriano** [comment]
Hello the icon is being taken from your profile picture. You can find the code [here](https://github.com/EmaSuriano/gatsby-starter-mate/blob/master/src/components/Helmet.js#L14). In case you want to another icon to another you can point to any other file by changing the `content` property on the tags inside `ReactHelmet`. Hope it helps!

**Comment by ShahrozTanveer** [comment]
on firefox it shows my profile picture favicon but on chrome it shows 
![fav](https://user-images.githubusercontent.com/31120765/89901138-2066b700-dbfe-11ea-8cca-e5f0cf7ebd9c.png)

**Comment by ShahrozTanveer** [comment]
in Helmet.js file when i do: ` console.log(`https:${profile.favicon32.src}`);` it  console `https://images.ctfassets.net/sho3lz351dxt/6nf3rNaaVaUqYcoAcciSeC/9d59849463003c4938d9e2606e79237e/prof.png?w=32&fl=progressive&q=50` which is my profile picture. But for some reason in public/ dir   `favicon-32x32.png` generated is 
<img width="16" alt="favicon-32x32" src="https://user-images.githubusercontent.com/31120765/89901917-37f26f80-dbff-11ea-9434-16fb9639eecf.png">

**Comment by ShahrozTanveer** [comment]
Site link: https://sharoztanveer.netlify.app/
it show different favicon on Chrome and FireFox .

**Comment by EmaSuriano** [comment]
I found where is the logic, the logo is actually "hardcoded" inside the `media` folder, and it's being loaded from the [manifest-config.json](https://github.com/EmaSuriano/gatsby-starter-mate/blob/master/gatsby-config.js#L19). You can replace the file directly and it should be fine after 👌

**Comment by ShahrozTanveer** [comment]
Working!. Thank you.
