### ISSUE TITLE
Updating Contentful About information returns errors for Profile 

### ISSUE THREAD

**Issue by alicemao23** [EmaSuriano/gatsby-starter-mate#577]
Hi, 

I'd like to update the favicon from the starter project. However if I update the Contentful content `About`, which is where the React Helmet is pulling its query Information from, the values for Profile becomes Nullify with a new Image upload 
```
profile: {
    appleIcon: null
    bigIcon: null
    favicon16: null
    favicon32: null
```

I tried updating the icon referenced in `Manifest-config` to the image I need, which works if I run a build and serve from the build, but it seems gatsby develop is pulling the Icon directly from Contentful, which is different than the local image 

How can I update both at the same time? 

Also this might be more of a contentful question but how does it show Profile to be a Media content on the Contentful content GUI, but with the query, it shows Profile having appleIcon, bigIcon, favicon16 & favicon32? I'm not sure how those individual values can be updated in Contentful

**Comment by EmaSuriano** [comment]
Hello @alicemao23, I never encountered this issue. I think it might be connected to the type/extension of the image. What format are you using (`png`, `jpg`, `svg`, etc.)?
