### ISSUE TITLE
update to theme

### ISSUE THREAD

**Issue by its-a-lisa** [EmaSuriano/gatsby-starter-mate#656]
Hello, 

Do you plan on updating this site as a theme instead of a starter?

**Comment by EmaSuriano** [comment]
Hello, I started working on it and then stop. The problem is that i might
have to create a new repo for the theme itself and keep the starter here as
it's.

It's in the roadmap for sure.

**Comment by EmaSuriano** [comment]
@its-a-lisa done! https://github.com/EmaSuriano/gatsby-starter-mate/pull/696
