### ISSUE TITLE
ELIFECYCLE error while running yarn start

### ISSUE THREAD

**Issue by boudhayan** [EmaSuriano/gatsby-starter-mate#67]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-mate@2.5.1 develop: `gatsby clean && gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-mate@2.5.1 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Boudhayan/.npm/_logs/2019-09-06T20_52_28_277Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I am getting the above error when I am running yarn start.

**Comment by boudhayan** [comment]
I got the fix.

**Comment by sakihayashi** [comment]
I got the same issue but couldn't fix. Could you tell me how you fixed it?

**Comment by boudhayan** [comment]
@sakihayashi 
please check https://github.com/EmaSuriano/gatsby-starter-mate/issues/65. Apply the same changes in your repo, it should fix the issue.
