### ISSUE TITLE
Write blog direct on website or Contentful instead of on Medium

### ISSUE THREAD

**Issue by GuillouTran** [EmaSuriano/gatsby-starter-mate#71]

**Comment by EmaSuriano** [comment]
Hello @GuillouTran,

This started used to have that, but then I realized that Medium provides an amazing writing experience and also increase your audience quite a lot. 

So the answer is, there is no feature to have "local" blogs. But I encourage you to write in Medium 😄

**Comment by GuillouTran** [comment]
But what if I really want to write in local?

**Comment by EmaSuriano** [comment]
There is no blogging feature in this starter I would suggest you choosing another because I don't have plans to add it to this project and adding it yourself will demand quite a lot of work.
