### ISSUE TITLE
Tutorial for editing the code in the theme

### ISSUE THREAD

**Issue by kanlanc** [EmaSuriano/gatsby-starter-mate#723]
Hello Ema,

I am having quite a bit of trouble understanding how to edit the code of the theme, I do not have problems with updating the content using contentful but instead the very code of the theme. I understand going to the node_modules and changing the code in the src wont help cause when deploying the changes will be erased, and I tried editing it in the src in the main and all i got are errors after errors.

Could you please make a tutorial on how to accomplish this please.

**Comment by EmaSuriano** [comment]
Hi @kanlanc I decided to expand the documentation of the project and improve the current customization section. Could you please take a look at this PR #725 and tell me if that solved your problem. Also, please feel to leave any comment on it 😄
