### ISSUE TITLE
Quick start fails with react updated to 17.0.2

### ISSUE THREAD

**Issue by nikolaenkov** [EmaSuriano/gatsby-starter-mate#735]
Hi, I have followed your tutorial video and everything worked fine except I got an error when trying to launch `yarn setup`

```
alexey% yarn setup
yarn run v1.22.10
warning ../../package.json: No license field
$ node ./bin/setup.js
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'contentful-import'
Require stack:
- /Users/alexey/Projects/ac/bin/setup.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/alexey/Projects/ac/bin/setup.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/alexey/Projects/ac/bin/setup.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This error may be overriden by the `--force` flag but in the end when the `yarn start` command is launched then you get

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
```

Most probably this is caused by the dependabot's [react update to 17.0.1](https://github.com/EmaSuriano/gatsby-starter-mate/commit/0dbf04e07f7f5036edf7fa6eaa7cc34731f970c6). 

I have downgraded it to 16.14.0 and everything worked like a charm.

**Comment by EmaSuriano** [comment]
Hello @nikolaenkov I am not able to reproduce this issue. Can you please let me know if it's a problem?

**Comment by nikolaenkov** [comment]
I have just reproduced it using a clean system:
```
brew install node
brew install gatsby-cli
brew install yarn
gatsby new mate-portfolio https://github.com/EmaSuriano/gatsby-starter-mate
cd mate-portfolio
yarn setup
```

I get:
```
alexey$ yarn setup
yarn run v1.22.10
$ node ./bin/setup.js
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module 'contentful-import'
Require stack:
- /Users/alexey/Projects/mate-portfolio/bin/setup.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/alexey/Projects/mate-portfolio/bin/setup.js:1:21)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/alexey/Projects/mate-portfolio/bin/setup.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It' s not a problem since there is work around. But I would consider checking dependencies. Most probably migration to react 17 should include updates to other components (I'm not a frontend specialist and cannot provide deeper details unfortunately).

**Comment by EmaSuriano** [comment]
Hello this issue should be solved by now 👍

**Comment by SabirKhanAkash** [comment]
> I have just reproduced it using a clean system:
> 
> ```
> brew install node
> brew install gatsby-cli
> brew install yarn
> gatsby new mate-portfolio https://github.com/EmaSuriano/gatsby-starter-mate
> cd mate-portfolio
> yarn setup
> ```
> 
> I get:
> 
> ```
> alexey$ yarn setup
> yarn run v1.22.10
> $ node ./bin/setup.js
> node:internal/modules/cjs/loader:930
>   throw err;
>   ^
> 
> Error: Cannot find module 'contentful-import'
> Require stack:
> - /Users/alexey/Projects/mate-portfolio/bin/setup.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:772:27)
>     at Module.require (node:internal/modules/cjs/loader:999:19)
>     at require (node:internal/modules/cjs/helpers:93:18)
>     at Object.<anonymous> (/Users/alexey/Projects/mate-portfolio/bin/setup.js:1:21)
>     at Module._compile (node:internal/modules/cjs/loader:1095:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:816:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/Users/alexey/Projects/mate-portfolio/bin/setup.js' ]
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> It' s not a problem since there is work around. But I would consider checking dependencies. Most probably migration to react 17 should include updates to other components (I'm not a frontend specialist and cannot provide deeper details unfortunately).

I'm not getting the prompt for giving the token, API. rather getting this error when I type "yarn setup". Please can you tell me how you fixed this ?

**Comment by EmaSuriano** [comment]
Hey, yeah the `setup` script was broken because I bump the version of `chalk` to 5 ... I downgrade the version to 4 and tested locally and should work now 👍 Sorry for the inconvenience.
