### ISSUE TITLE
Invalid hook call. Hooks can only be called inside the body of a function component

### ISSUE THREAD

**Issue by OwenWheatley** [EmaSuriano/gatsby-starter-mate#77]
_"Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem."_

This error comes up after running `npm start` when attempting to view mate on localhost. `npm run setup` had been ran successfully and linked with contentful.

After reading the react-invalid-hook-call facebook provides and going through the steps they recommend. `npm ls react-dom` returns a version of react greater than 16.8.0 so it's not that the project is missing hooks.

When running `npm ls react` to check if there is a duplicate react within the project you can see that there is.
![duplicate react](https://user-images.githubusercontent.com/22055189/69350013-b32a8480-0c70-11ea-9ec8-3dc303455226.PNG)

Maybe I'm wrong about this being a problem with the starter and it's my own development environment that is messed up but I haven't had any problems running other starters? Hoping someone can help with this ^.^

**Comment by EmaSuriano** [comment]
Hello @OwenWheatley did you make any changes in the codebase of the starter or just the basic setup?

**Comment by OwenWheatley** [comment]
Just did the basic starter, haven't changed the codebase. Even did a fresh gatsby new to double check. 
Had a look to try and fix it and came across: https://github.com/facebook/react/issues/13991
Adding this into the script: 
`"prestart": "npm-link-shared ./node_modules/<other package>/node_modules . react"`
could help though I'm unsure of what to put in the <other package> section as I'm unfamiliar with link-shared.

Here are the stack frames that came up if that helps at all
![error](https://user-images.githubusercontent.com/22055189/69359814-394ec700-0c81-11ea-847d-c2250726ddf9.PNG)

Have you done a gatsby new of mate recently?

**Comment by OwenWheatley** [comment]
So after a morning of battling this issue, I've tried adding:
`"prestart": "npm-link-shared ./node_modules/gatsby/node_modules . react",`
to the start of the scripts to try and deal with the two reacts.

It looked like Gatsby had react in the package.json and then inside the node_modules of Gatsby is the Gatsby cli which inside of that has a package.json file also including react in it.
This seemed to have been why `npm ls react` returned the two reacts within the project.
![duplicate react](https://user-images.githubusercontent.com/22055189/69433941-82ac1e80-0d34-11ea-9e90-094832a803bd.PNG)

So after then going into the gatsby cli package.json and removing react then doing `npm i` again it has removed this duplication so now `npm ls react` showed just one react within the project.
![1 version of react now](https://user-images.githubusercontent.com/22055189/69433999-a1aab080-0d34-11ea-8e74-4dc2fa312f93.PNG)

However when trying to run it the same error message persists.

Is anyone else able to try creating a new gatsby project with this starter to see what they run into? Just really want to confirm that this isn't just an issue for me.

**Comment by OwenWheatley** [comment]
So I've not been able to find anyone else who is up for running the mate starter (small circle I guess haha). I ran it on another computer I have and wanted to try this time doing it completely via the **cygwin** terminal as I noticed when you do 
`gatsby new mate-portfolio https://github.com/EmaSuriano/gatsby-starter-mate`
It actually runs through the `npm start` scripts which includes attempting the `sed` which won't work in a windows terminal. I figured maybe this was why react was being duplicated? Apparantly not though as I still end up with:
![duped react](https://user-images.githubusercontent.com/22055189/69488457-6a85ed80-0e61-11ea-8376-d82db49db979.PNG)

After doing this I was still met with the same problem. 
![react hooks broken](https://user-images.githubusercontent.com/22055189/69488394-d74cb800-0e60-11ea-8e95-13c91a8b4268.PNG)
But with some more detail at least.

I'm not too sure where to go at this point but will keep trying, I'm looking into using `npm-dedupe` (https://docs.npmjs.com/cli/dedupe.html).

If anyone can provide any assistant or advice on what to go after that would be great. It would be nice to know if anyone else is having the same problem getting _mate_ going :)

**Comment by EmaSuriano** [comment]
Hello @OwenWheatley, sorry for the huge delay! So I made a quick test by bootstrapping a new instance and besides the issues of the latest version `gatsby-source-contentful` when it installs a different version from the one inside `package-lock.json` it works perfectly in my computer.

Do you still have the same issues?

**Comment by OwenWheatley** [comment]
What OS are you on? What is the issue with the latest version of gatsby-source-contentful that you speak of? Is there something else besides what is in the readme that I must do for the setup.

I am afraid I am still having the same issue... =/

**Comment by EmaSuriano** [comment]
I'm using macOS Mojave and I tried in a Windows 10 machine using Git bash as the terminal. In both cases, it worked 🤔

Btw, I just merged a new pr (#90)where I changed the package manager from `npm` to `yarn`. This change may have fixed your issue, can you please try again?  😄

**Comment by OwenWheatley** [comment]
Hmm just tried this using yarn and it didn't work.. Just to check what you've said in the docs matches, there it says to make sure the package manager is npm but then here you have changed to yarn?
![package manager](https://user-images.githubusercontent.com/22055189/71411958-4c1f3780-2643-11ea-95c9-f9eaab7c737a.PNG)

What is the issue with the latest version of `gatsby-source-contentful` installing a different one that you mentioned further up? Is there anything further there that I need to do when bootstrapping a new instance?

**Comment by EmaSuriano** [comment]
Hello, I removed the warning from the docs because now it's not necessary :)

The issue with `gatsby-source-contentful` and `gatsby` is tracked in [this issue](https://github.com/gatsbyjs/gatsby/issues/15344).

Do you still have the react version issue or is it different now?

**Comment by OwenWheatley** [comment]
Haven't had chance to go much further into it but I still had the issue. I'll just try hosting it and should be fine :D Probs spin up a linux vm to try it out. Thanks for all your help so far :)

**Comment by conspireagency** [comment]
I've run into some weird issues with this happening in Gatsby.  If it comes up again for anyone, you might want  to try deleting .cache, node_modules, public folders and package-lock.json.  Then run a full npm install again before firing Gatsby back up.
