### ISSUE TITLE
Medium data fetching error - failing to build on Netlify

### ISSUE THREAD

**Issue by Jordhan-Carvalho** [EmaSuriano/gatsby-starter-mate#80]
Hey there, 
Just tried to update my website based on this starter and I'm getting an error when trying to redeploy on netlify....

```
Fetch Contentful data: 429.336ms
2:55:36 PM: { Error: Request failed with status code 403
...

- 2:55:36 PM:   config:
- 2:55:36 PM:    { url:
- 2:55:36 PM:       'https://medium.com/@mate.starter/latest?format=json&limit=100',
- 2:55:36 PM:      method: 'get',
- 2:55:36 PM:      headers:
- 2:55:36 PM:       { Accept: 'application/json, text/plain, */*',
- 2:55:36 PM:         'User-Agent': 'axios/0.19.0' },
- 2:55:36 PM:      transformRequest: [ [Function: transformRequest] ],
- 2:55:36 PM:      transformResponse: [ [Function: transformResponse] ],
- 2:55:36 PM:      timeout: 0,
- 2:55:36 PM:      adapter: [Function: httpAdapter],
- 2:55:36 PM:      xsrfCookieName: 'XSRF-TOKEN',
- 2:55:36 PM:      xsrfHeaderName: 'X-XSRF-TOKEN',
- 2:55:36 PM:      maxContentLength: -1,
- 2:55:36 PM:      validateStatus: [Function: validateStatus],
- 2:55:36 PM:      data: undefined },
```
It seems like an error trying to hit the medium endpoint... since i dont really use the medium feature, what should i do to remove the said request?

**Comment by EmaSuriano** [comment]
Hello, this issue should be fixed with the latest commit of the repo. Please try to set up your project and now it should work :) 

PD: you don't need to create a new Contentful Space, just run `gatsby new mate-portfolio https://github.com/EmaSuriano/gatsby-starter-mate` again and change your values inside the `.env`.
