### ISSUE TITLE
Why the src folder empty?

### ISSUE THREAD

**Issue by byprakoso** [EmaSuriano/gatsby-starter-mate#849]

**Comment by byprakoso** [comment]
I cannot change the color scheme on color.js

**Comment by EmaSuriano** [comment]
Hye @byprakoso do you have a link to your repo so then I can take a look?

**Comment by byprakoso** [comment]
https://github.com/byprakoso/by-portfolio

**Comment by EmaSuriano** [comment]
I wrote a section to tackle this issue --> https://github.com/EmaSuriano/gatsby-starter-mate#theming

You have to define a `colors.json` file inside the following path of your project `src/gatsby-theme-mate` with the following structure:

```json
{
  "text": "#333333",
  "background": "#FFFFFF",
  "muted": "#f0e6f6",
  "primary": "#7c37ad",
  "secondary": "#ff4081"
}
```

**Comment by byprakoso** [comment]
So I just add new file `color.json` manually in folder `src/gatsby-theme-mate` ? I'll try it after this, but why that folder empty? because this is the second time I clone this repo, at first there are lot of file inside your `src` folder.

**Comment by EmaSuriano** [comment]
Closed due to inactivity.
