### ISSUE TITLE
Cannot change social media

### ISSUE THREAD

**Issue by byprakosoo** [EmaSuriano/gatsby-starter-mate#881]
I want to change my social media account from Twitter to dribble. but after I save the contentful, the twitter icon is just gone and dribblble icon won't show up in this portfolio web.

**Comment by EmaSuriano** [comment]
I addressed this issue inside the Customization section, please try adding the icon of Dribble and see if your issue is solved.

**Comment by byprakoso** [comment]
Thank you so much @EmaSuriano

**Comment by byprakoso** [comment]
Hi @EmaSuriano , I want to add my Codepen link in this web, can you add the Codepen's icon too? Thank you before.

**Comment by EmaSuriano** [comment]
Hey @byprakoso, as I mentioned above, I included the steps to change the icons to whatever you preferred. In your case, you need to include the following line inside `src/gatsby-theme-mate/icons.js`:

```diff
import {
  faMedium,
- faTwitter,
+ faDribble
  faGithub,
} from '@fortawesome/free-brands-svg-icons';
import {
  faGlobe,
  faEnvelope,
  faCoffee,
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = [
  faMedium,
- faTwitter,
+ faDribble,
  faGithub,
  faGlobe,
  faEnvelope,
  faCoffee,
  fa
];
```

Please let me know if you still can't see the icon :)
